import { RepositoryCommits } from './gitProvider';

export class ReportGenerator {
    public static generateMarkdown(repos: RepositoryCommits[]): string {
        const today = new Date();
        const year = today.getFullYear();
        const month = String(today.getMonth() + 1).padStart(2, '0');
        const day = String(today.getDate()).padStart(2, '0');
        const dateString = `${year}-${month}-${day}`;

        let markdown = `# Git Activity Report\n**Date:** ${dateString}\n\n`;

        if (repos.length === 0) {
            markdown += `*No commits found for today across your workspace repositories.*\n`;
            return markdown;
        }

        for (const repo of repos) {
            markdown += `## Repository: ${repo.repositoryName}\n\n`;
            
            for (const commit of repo.commits) {
                const commitDate = commit.authorDate || commit.commitDate || new Date();
                const hours = String(commitDate.getHours()).padStart(2, '0');
                const minutes = String(commitDate.getMinutes()).padStart(2, '0');
                const seconds = String(commitDate.getSeconds()).padStart(2, '0');
                const timeString = `${hours}:${minutes}:${seconds}`;
                
                markdown += `- **Branch:** \`${commit.branchName}\`\n`;
                markdown += `- **Timestamp:** ${timeString}\n`;
                markdown += `- **Commit:** \`${commit.hash.substring(0, 7)}\`\n`;
                markdown += `- **Commit message:**\n  > ${commit.message.replace(/\n/g, '\n  > ')}\n\n`;
            }
        }

        markdown += `---\n*Generated by Git Activity Tracker*\n`;
        return markdown;
    }
}
