import { RepositoryCommits } from './gitProvider';

export class ReportGenerator {
    public static generateMarkdown(repos: RepositoryCommits[]): string {
        const today = new Date();
        const dateString = today.toLocaleDateString(undefined, {
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
        });

        let markdown = `# Git Activity Report\n**Date:** ${dateString}\n\n`;

        if (repos.length === 0) {
            markdown += `*No commits found for today across your workspace repositories.*\n`;
            return markdown;
        }

        for (const repo of repos) {
            markdown += `## Repository: ${repo.repositoryName}\n\n`;
            
            for (const commit of repo.commits) {
                const commitDate = commit.authorDate || commit.commitDate || new Date();
                const timeString = commitDate.toLocaleTimeString(undefined, {
                    hour: '2-digit', minute: '2-digit'
                });
                
                // First line is the title, the rest is description
                const messageParts = commit.message.split('\n');
                const title = messageParts[0];
                
                markdown += `### ${title}\n`;
                markdown += `- **Time:** ${timeString}\n`;
                markdown += `- **Commit:** \`${commit.hash.substring(0, 7)}\`\n`;
                
                if (messageParts.length > 1) {
                    const body = messageParts.slice(1).join('\n').trim();
                    if (body) {
                        markdown += `- **Details:**\n  > ${body.replace(/\n/g, '\n  > ')}\n`;
                    }
                }
                markdown += `\n`;
            }
        }

        markdown += `---\n*Generated by Git Activity Tracker*\n`;
        return markdown;
    }
}
